### ISSUE TITLE
Stuck on "mounting drive(s)" with hiyaCFW

### ISSUE THREAD

**Issue by frnklnchng** [RocketRobz/GodMode9i#53] opened 2020-03-23 04:33 UTC
Tested on DSi, FAT 32 SD card. Application just freezes on start at "mounting drive(s)".

**Comment by RocketRobz** [comment] 2020-03-23 04:40
Try holding Y before the freeze.

**Comment by frnklnchng** [comment] 2020-03-23 04:45
Tried that - still stuck at "mounting drives". I tried just leaving it there for a few minutes and no progress.

**Comment by RocketRobz** [comment] 2020-03-23 04:46
Try immediately removing the SD card, after the GM9i logo shows.

**Comment by frnklnchng** [comment] 2020-03-23 04:52
Still nothing, any other suggestions? I haven't tried running an older release yet.

**Comment by RocketRobz** [comment] 2020-03-23 04:52
What are you launching GM9i with?

**Comment by frnklnchng** [comment] 2020-03-23 04:54
Using the latest TWiLight.

**Comment by RocketRobz** [comment] 2020-03-23 04:57
What are the per-game settings set for GM9i?

**Comment by frnklnchng** [comment] 2020-03-23 05:01
I'm not sure where I can find that out from, but I haven't been able to run it at all, nor have I changed any settings.

**Comment by RocketRobz** [comment] 2020-03-23 05:01
In the TWLMenu++ ROM menu, press Y.

**Comment by frnklnchng** [comment] 2020-03-23 05:04
Gotcha, wasn't sure what you meant. But, I don't get any option for settings when I open the Y menu.

**Comment by papin97** [comment] 2020-03-25 06:50
I get the same issue (holding Y button doesn't solve the issue).
Here's per-game setting that I use:
- Language: Default
- RAM Disk: None
- Direct Boot: Yes
- Run in: DSi Mode
- ARM9 CPU Speed: 133 MHz (TWL)
- VRAM Boost: On
- Bootstrap: Default

**Comment by RocketRobz** [comment] 2020-04-05 22:24
It appears the issue is caused by using the app in HiyaCFW.

**Comment by R-YaTian** [comment] 2020-04-06 02:39
> It appears the issue is caused by using the app in HiyaCFW.

Ha, I think this is because GM9i cannot mount nand after access HiyaCFW.

**Comment by ApacheThunder** [comment] 2020-04-13 14:36
I've recently updated GodMod9i to the latest build and I'm now experiencing this issue too. However I have GodMode9i setup as DSiWare so I launch it from System Menu and not from HiyaCFW or Twilight.

**Comment by stuffi3000** [comment] 2020-05-28 16:40
I'm having the same issues. Is there and fix in sight? Or maybe a temporary solution like "hold this button to not mount NAND". Because I have no idea how to apply the fix from @ApacheThunder haha

**Comment by SNBeast** [comment] 2020-06-07 02:34
I have this same issue. I find that a way to bypass it is to load GodMode9i from Unlaunch.

**Comment by stuffi3000** [comment] 2020-06-09 14:33
> 
> 
> I have this same issue. I find that a way to bypass it is to load GodMode9i from Unlaunch.

That's a great workaround, thank you!

**Comment by RocketRobz** [comment] 2020-07-15 03:41
Fixed in v2.4.0, by holding X.

**Closed by RocketRobz** 2020-07-15 03:41 UTC
Labels: bug
